---
# https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
- name: install grafana
  become: true
  become_user: root
  block:
    - name: install required packages
      register: task_result
      apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present
      until: task_result is succeeded
      retries: 5
      delay: 10

    - name: add grafana repository signing key
      register: task_result
      apt_key:
        url: https://apt.grafana.com/gpg.key
        keyring: /usr/share/keyrings/grafana.key
        state: present
      until: task_result is succeeded
      retries: 5
      delay: 10

    - name: add grafana repository
      register: task_result
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
        state: present
        filename: grafana
      until: task_result is succeeded
      retries: 5
      delay: 10

    - name: install grafana
      register: task_result
      apt:
        name: grafana
        state: present
      until: task_result is succeeded
      retries: 5
      delay: 10

- name: configure grafana
  block:
    - name: setup dashboard
      copy:
        src: "dashboard.json"
        dest: "/etc/grafana/provisioning/dashboards/dashboard.json"

    - name: setup datasource
      template:
        src: datasource.yml.j2
        dest: /etc/grafana/provisioning/datasources/datasource.yml

    - name: configure grafana
      template:
        src: grafana.ini.j2
        dest: /etc/grafana/grafana.ini
      notify: restart_grafana_server

- name: flush handlers
  meta: flush_handlers

- name: pause for 5 second wait starting grafana
  pause:
    seconds: 5

- name: "check if grafana is accessible"
  uri:
    url: http://127.0.0.1:{{ port }}
    status_code: 200
  register: _grafana_server_status
  until: _grafana_server_status.status == 200
  retries: 60
  delay: 1

- name: change admin password for grafana gui
  shell: "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: _grafana_admin_password
  until: _grafana_admin_password.rc == 0
