---
# - hosts: alert_manager
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#      - alert_manager

# ------------------
# ------ DONE ------
# ------------------

# - hosts: node_exporter
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - node_exporter

- hosts: backend
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - port: 5000
    - work_dir: /root/{{repo_name}}
    - testing_url: http://localhost:{{ port }}/metrics
  roles:
    - nodejs
    - application

- hosts: frontend
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - port: 3000
    - work_dir: /root/{{repo_name}}/client
    - testing_url: http://localhost:{{ port }}
  roles:
    - nodejs
    - application
# - hosts: prometheus
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - prometheus

# - hosts: grafana
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - grafana
