---
# - hosts: alert_manager
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#      - alert_manager

# - hosts: node_exporter
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - node_exporter

- hosts: frontend
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - frontend
# ------------------
# ------ DONE ------
# ------------------

# - hosts: prometheus
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - prometheus
# - hosts: grafana
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - grafana
