---
- hosts: alert_manager
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alert_manager
# - hosts: backend
#   become: yes
#   become_user: root
#   become_method: sudo
#   vars:
#     - app_port: 5000
#     - server_domain: "{{ hostvars[groups['backend'][0]]['ansible_host'] }}"
#     - work_dir: /root/{{ repo_name }}
#     - testing_url: http://{{ server_domain }}:{{ app_port }}/metrics
#   roles:
#     - nodejs
#     - application
#     - node_exporter

# - hosts: frontend
#   gather_facts: true
#   become: yes
#   become_user: root
#   become_method: sudo
#   vars:
#     - app_port: 3000
#     - server_domain: "{{ hostvars[groups['frontend'][0]]['ansible_host'] }}"
#     - work_dir: /root/{{repo_name}}/client
#     - testing_url: http://{{ server_domain }}:{{ app_port }}
#   roles:
#     - nodejs
#     - application
#     - node_exporter

# - hosts: prometheus
#   gather_facts: true
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - prometheus

# - hosts: grafana
#   become: yes
#   become_user: root
#   become_method: sudo
#   vars_files:
#     - roles/prometheus/vars/main.yml
#   roles:
#     - grafana
