---
# - hosts: alert_manager
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#      - alert_manager

# - hosts: node_exporter
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - node_exporter

- hosts: backend
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - backend
# ------------------
# ------ DONE ------
# ------------------

## TODO: merge front end and backend run in 1 role "auto setup"
# - hosts: frontend
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - frontend

# - hosts: prometheus
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - prometheus
# - hosts: grafana
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - grafana
