FROM ubuntu:20.04

WORKDIR /root

RUN apt update -y \
   && apt install sudo -y \
   && apt install openssh-server -y

ADD ./dockerfile/entrypoint.sh /root/
RUN chmod +x entrypoint.sh

ENTRYPOINT [ "/root/entrypoint.sh" ]
